# Yoshida-Compensation Project Configuration

[projector]
gamma = 2.2
width = 1920
height = 1080
pos_x = 5360            # プロジェクタウィンドウの X 位置 (1920 + 3440)
pos_y = 0               # プロジェクタウィンドウの Y 位置

[camera]
backend = "canon_edsdk" # "canon_edsdk" | "opencv"
av = "8"
tv = "1/15"             # 分数表記・小数どちらも可
iso = "400"
image_quality = "LR"
device_index = 0        # OpenCV backend 使用時のカメラインデックス
wait_key_ms = 200       # パターン表示後の待機時間 (ms)

[paths]
c2p_map = ""            # C2P correspondence map (.npy)
p2c_map = ""            # P2C correspondence map (.npy)
warp_method = "c2p"     # "c2p" | "p2c"
rpcc_matrix = ""        # RPCC matrix (.npy)
target_image_dir = "data/target_images"
linear_pattern_dir = "data/linear_proj_patterns"
inv_gamma_pattern_dir = "data/inv_gamma_proj_patterns"
captured_image_dir = "data/captured_images"
compensation_image_dir = "data/compensation_images"
inv_gamma_comp_dir = "data/inv_gamma_comp_images"

[compensation]
num_divisions = 3               # パターン生成の分割数
safety_margin = 0.5             # バッチサイズ推定時の安全マージン
min_batch_size = 256            # 最小バッチサイズ
use_gpu = true                 # 色混合行列計算で GPU を使用するか
